---
grails:
    profile: web-plugin

info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'

org:
    grails:
        jaxrs:
            enabled: false